version: 2

sources:
  - name: bronze
    database: LOAN_DEFAULT_DB
    schema: BRONZE

    tables:
      - name: accepted_loans
        identifier: ACCEPTED_LOANS

      - name: rejected_loans
        identifier: REJECTED_LOANS